### ISSUE TITLE
Merged/forwarded author IDs

### ISSUE THREAD

**Issue by stefano-baruffaldi** [sosia-dev/sosia#21]
When a author id is merged and does not exist anymore, sosia provides an error, but from scopus one can see the warning. Maybe this can be adjusted...

```
[57201609495, 7004299063]
E:\Anaconda3\lib\site-packages\scopus\author_retrieval.py:215: UserWarning: Author profile with ID 57201609495 has been merged and the main profile is now one of 7004299063, 57205593771.  Please update your records manually.  Functionality of this object is reduced.
  warn(text, UserWarning)
Traceback (most recent call last):

  File "<ipython-input-1-1f5517ca9f0e>", line 47, in <module>
    pub_margin=0.2)

  File "E:\Anaconda3\lib\site-packages\sosia\sosia.py", line 162, in __init__
    Scientist.__init__(self, self.identifier, year, refresh)

  File "E:\Anaconda3\lib\site-packages\sosia\classes\scientist.py", line 210, in __init__
    self._name = ", ".join([au.surname, au.given_name])

TypeError: sequence item 0: expected str instance, NoneType found
```

**Comment by Michael-E-Rose** [comment]
But is this not what we want? Have an error, such that the user provides the correct ID? Or what kind if error-handling would you suggest?

**Comment by stefano-baruffaldi** [comment]
I thought, this should appear as  a warning directly in sosia. But maybe is also more correct like this? ..in any case it is a minor issue

**Comment by Michael-E-Rose** [comment]
pybliometrics raises a warning in two cases:
- The author ID gets forwarded to the new profile, so that the old ID is identical to the new ID
- The author ID is old but does not forward because multiple new profiles are the possible new profile

Does that solve this issue?

**Comment by Michael-E-Rose** [comment]
In the current version of sosia, the manifests as this: In the Author Search and the Scopus Search API, the IDs get forwarded, but for the results from the Author Search API, we use the ID returned by Scopus - which is the new one.

So, when using the Author Search API in the first step of `.find_matches()`, one of three things happens:
- if the new ID is _not also_ in the set of candidates, we only get information for the new one, which we continue to use. All is fine.
- if the new ID is also in the set of candidates, we duplicate information (since the queries for the old ID and the new ID return the same new ID). Ever since I enforce the UNIQUE constraint during the SQL inserting phase, sosia throws an error. 
- if the new ID is already in the database, but we query for the old ID and try to insert the data using the new ID, sosia throws an error.

We have to solve that.
